---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-qwen-server-vision
  annotations:
    kubernetes.io/pvc-protection: "false"  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 900Gi
  storageClassName: gp3  # Uses ebs.csi.eks.amazonaws.com provisioner for EKS Auto Mode
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-qwen-server-vision
  labels:
    app: vllm-qwen-server-vision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-qwen-server-vision
  template:
    metadata:
      labels:
        app: vllm-qwen-server-vision
    spec:
      # Updated nodeSelector to target GPU instances specifically
      nodeSelector:
        kubernetes.io/arch: amd64
        #nvidia.com/gpu.present: "true"
      # Updated tolerations to match the taint on the GPU nodepool
      
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: vllm-qwen-server-vision
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "32Gi"
      containers:
      - name: vllm-qwen-server-vision
        #image: vllm/vllm-openai:latest
        image: public.ecr.aws/deep-learning-containers/vllm:0.12.0-gpu-py312-cu129-ubuntu22.04-ec2-v1.0-soci
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve Qwen/Qwen2.5-VL-7B-Instruct  --enable-auto-tool-choice --tool-call-parser hermes  --trust-remote-code --max-num-batched-tokens 8192  --max-num-seqs 8 --max-model-len 8192 --dtype bfloat16 --tensor-parallel-size 4 --gpu-memory-utilization 0.90"
          
        ]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: token
        - name: OMP_NUM_THREADS
          value: "8"  
        - name: VLLM_LOGGING_LEVEL
          value: "DEBUG"  
        - name: VLLM_DISABLE_COMPILE_CACHE
          value: "0"  
        # - name: PYTORCH_CUDA_ALLOC_CONF
        #   value: "max_split_size_mb:512,expandable_segments:True"
        - name: CUDA_VISIBLE_DEVICES
          value: "0,1,2,3"
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 64Gi
            nvidia.com/gpu: "4"
          requests:
            cpu: "22"
            memory: 64Gi
            nvidia.com/gpu: "4"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 240
          periodSeconds: 10
          failureThreshold: 30
          successThreshold: 1

          
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 240
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: vllm-qwen-server-vision
spec:
  ports:
  - name: http-vllm-qwen-server-vision
    port: 8000
    protocol: TCP
    targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: vllm-qwen-server-vision
  sessionAffinity: None
  type: ClusterIP          



