# Updated for EKS Auto Mode compatibility
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
#Compatble with EKS AutoMode    
provisioner: ebs.csi.eks.amazonaws.com 
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: Immediate