---
# Graviton Node Pool for ARM-based workloads
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: graviton-inference
spec:
  limits:
    cpu: 512
    memory: 4096Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30m
  template:
    metadata:
      labels:
        model-inferencing: "graviton-inference"
        ray-control-plane: "false"
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: graviton-inference  
      expireAfter: 8h
      requirements:
        - key: eks.amazonaws.com/instance-category
          operator: In
          values:
            - c
            - m
            - r       
        #- key: eks.amazonaws.com/instance-size
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values: ["6"]
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64
        - key: kubernetes.io/os
          operator: In
          values: 
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: eks.amazonaws.com/instance-size
          operator: In
          values:
            - 2xlarge
            - 4xlarge
            - 8xlarge
            - 12xlarge
            - 16xlarge  
---
# Graviton NodeClass
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: graviton-inference
spec:
  #ephemeral storage spec below
  ephemeralStorage:
    iops: 10000
    size: 100Gi
    throughput: 256
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Disabled
  #role: inference-cluster-am-eks-auto-20251009204412656600000004
  role: ${CLUSTER_NAME}-eks-auto-20251209194501631700000003
  securityGroupSelectorTerms:
  #- id: sg-0aa207610e365e734
    - tags:
        #Name: inference-cluster-am-node
       Name: eks-cluster-sg-${CLUSTER_NAME}-*
  snatPolicy: Random
  subnetSelectorTerms:
    - tags:
       Name: ${CLUSTER_NAME}-private-secondary-*
       karpenter.sh/discovery: ${CLUSTER_NAME}
       kubernetes.io/role/internal-elb: "1"
  tags:
    Name: karpenter-graviton-karpenter
    Environment: dev
    karpenter.sh/discovery: ${CLUSTER_NAME}
    model-inferencing: "graviton-inference"
    ray-control-plane: "false"
    Provisioned-By: awslabs/ai-on-eks/tree/main/infra/solutions/inference-ready-cluster
