---
# x86 Node Pool for x86-based workloads
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: x86-inference
spec:
  limits:
    cpu: 512
    memory: 4096Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
  template:
    metadata:
      labels:
        model-inferencing: "x86-inference"
        ray-control-plane: "false"
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: x86-inference
      expireAfter: 8h
      taints:
        - key: "model-inferencing"
          value: "x86-inference"
          effect: NoSchedule
      requirements:
        - key: eks.amazonaws.com/instance-category
          operator: In
          values:
            - c
            - m
            - r
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values: ["6"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: eks.amazonaws.com/instance-size
          operator: In
          values:
            - 2xlarge
            - 4xlarge
            - 8xlarge
            - 12xlarge
            - 16xlarge

---
# X86 Node class
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: x86-inference
spec:
  #ephemeral storage spec below
  ephemeralStorage:
    iops: 16000
    size: 100Gi
    throughput: 512
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Disabled
  role: ${CLUSTER_NAME}-eks-auto-20251209194501631700000003
  securityGroupSelectorTerms:
  #- id: sg-0aa207610e365e734
    - tags:
        #Name: inference-cluster-am-node
       Name: eks-cluster-sg-${CLUSTER_NAME}-*
  snatPolicy: Random
  subnetSelectorTerms:
    - tags:
       Name: ${CLUSTER_NAME}-private-secondary-*
       karpenter.sh/discovery: ${CLUSTER_NAME}
       kubernetes.io/role/internal-elb: "1"  
  tags:
    Name: karpenter-x86-karpenter
    Environment: dev
    karpenter.sh/discovery: ${CLUSTER_NAME}
    model-inferencing: "x86-inference"
    ray-control-plane: "false"
    Provisioned-By: awslabs/ai-on-eks/tree/main/infra/solutions/inference-ready-cluster
