---
# Graviton Node Pool for ARM-based workloads
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: graviton
spec:
  limits:
    cpu: 512
    memory: 4096Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30m
  template:
    metadata:
      labels:
        model-inferencing: "graviton"
        ray-control-plane: "false"
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: graviton  
      expireAfter: 8h
      requirements:
        - key: eks.amazonaws.com/instance-category
          operator: In
          values:
            - c
            - m
            - r       
        #- key: eks.amazonaws.com/instance-size
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values: ["6"]
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64
        - key: kubernetes.io/os
          operator: In
          values: 
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: eks.amazonaws.com/instance-size
          operator: In
          values:
            - 2xlarge
            - 4xlarge
            - 8xlarge
            - 12xlarge
            - 16xlarge  
      terminationGracePeriod: 24h0m0s      
---
# Graviton NodeClass
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: graviton
spec:
  #ephemeral storage spec below
  ephemeralStorage:
    iops: 10000
    size: 300Gi
    throughput: 256
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Disabled
  role: ${role}
  securityGroupSelectorTerms:
    - id: ${cluster_security_group_id}     
  snatPolicy: Random
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${cluster_name}"
        Name: "${cluster_name}-private-secondary*" # Only secondary cidr subnets
  tags:
    Name: karpenter-graviton-karpenter
    Environment: dev
    karpenter.sh/discovery: ${cluster_name}
    model-inferencing: "graviton"
    ray-control-plane: "false"
    Provisioned-By: awslabs/ai-on-eks/tree/main/infra/solutions/inference-ready-cluster
